from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

import chromadb
from chromadb import Collection

from ..config import AppConfig
from .chunking import TextChunk
from .embeddings import EmbeddingBackend
from .document_summary import DocumentSummary


@dataclass
class VectorStoreManager:
    client: chromadb.PersistentClient
    embedding_backend: EmbeddingBackend

    def _collection_name(self, notebook_id: str) -> str:
        return f"notebook_{notebook_id}"

    def get_collection(self, notebook_id: str) -> Collection:
        return self.client.get_or_create_collection(name=self._collection_name(notebook_id))

    def delete_notebook_collections(self, notebook_id: str) -> None:
        """Drop the chunk and summary collections for a deleted notebook.

        Both deletes are best-effort: missing collections are not an error.
        """
        for name in (
            self._collection_name(notebook_id),
            self._doc_summaries_collection_name(notebook_id),
        ):
            try:
                self.client.delete_collection(name=name)
            except Exception:
                # Collection may not exist yet for never-ingested notebooks.
                pass

    def delete_document(self, notebook_id: str, source_path: str) -> int:
        """Remove all chunks and the summary for a single document. Returns
        the number of chunks removed (0 if the document wasn't indexed)."""
        removed = 0
        try:
            collection = self.get_collection(notebook_id)
            existing = collection.get(where={"source_path": source_path})
            ids = existing.get("ids") or []
            if ids:
                collection.delete(ids=ids)
                removed = len(ids)
        except Exception:
            pass

        # Summaries live in a sibling collection; also best-effort.
        try:
            summaries_collection = self.client.get_collection(
                name=self._doc_summaries_collection_name(notebook_id)
            )
            existing = summaries_collection.get(where={"source_path": source_path})
            ids = existing.get("ids") or []
            if ids:
                summaries_collection.delete(ids=ids)
        except Exception:
            pass

        return removed

    # Embedding all chunks of a 500-page PDF in one call to `model.encode`
    # can allocate several GB and OOM. Batching keeps peak memory bounded.
    _EMBED_BATCH = 64

    def add_chunks(self, notebook_id: str, chunks: Iterable[TextChunk]) -> int:
        chunk_list = list(chunks)
        if not chunk_list:
            return 0

        collection = self.get_collection(notebook_id)
        total = 0
        for start in range(0, len(chunk_list), self._EMBED_BATCH):
            batch = chunk_list[start : start + self._EMBED_BATCH]
            documents = [chunk.text for chunk in batch]
            embeddings = self.embedding_backend.embed(documents)
            metadatas = [
                {"source_path": chunk.source_path, "order": chunk.order}
                for chunk in batch
            ]
            ids = [chunk.chunk_id for chunk in batch]

            # upsert, not add — a re-upload of the same file would have failed
            # with DuplicateIDError mid-batch, leaving the collection in an
            # inconsistent state (some chunks present, some not).
            collection.upsert(
                ids=ids,
                documents=documents,
                metadatas=metadatas,
                embeddings=embeddings,
            )
            total += len(batch)
        return total

    def query(
        self,
        notebook_id: str,
        query: str,
        top_k: int = 5,
        where: dict | None = None,
    ) -> dict:
        """
        Query the collection using embeddings generated by our configured backend.
        Avoid relying on Chroma's built-in embedder (which may use a different dimension).
        """
        collection = self.get_collection(notebook_id)
        query_emb = self.embedding_backend.embed([query])
        query_kwargs = {
            "query_embeddings": query_emb,
            "n_results": top_k,
        }
        if where:
            try:
                query_kwargs["where"] = where
                return collection.query(**query_kwargs)
            except Exception:
                # Fallback to unfiltered query if the where syntax is unsupported
                pass
        return collection.query(**query_kwargs)

    async def aquery(
        self,
        notebook_id: str,
        query: str,
        top_k: int = 5,
        where: dict | None = None,
    ) -> dict:
        """Async variant: embedding runs on a threadpool so the event loop
        stays responsive during chat stream setup."""
        collection = self.get_collection(notebook_id)
        query_emb = await self.embedding_backend.aembed([query])
        query_kwargs = {
            "query_embeddings": query_emb,
            "n_results": top_k,
        }
        if where:
            try:
                query_kwargs["where"] = where
                return collection.query(**query_kwargs)
            except Exception:
                pass
        return collection.query(**query_kwargs)
    
    async def aquery_across_notebooks(
        self,
        notebook_ids: list[str],
        query: str,
        top_k: int = 5,
    ) -> dict:
        """Async wrapper for cross-notebook query; embeds on a threadpool."""
        query_emb = await self.embedding_backend.aembed([query])
        return self._query_across_notebooks_impl(notebook_ids, query_emb, top_k)

    def query_across_notebooks(
        self,
        notebook_ids: list[str],
        query: str,
        top_k: int = 5,
    ) -> dict:
        query_emb = self.embedding_backend.embed([query])
        return self._query_across_notebooks_impl(notebook_ids, query_emb, top_k)

    def _query_across_notebooks_impl(
        self,
        notebook_ids: list[str],
        query_emb: list[list[float]],
        top_k: int,
    ) -> dict:
        """
        Query multiple notebook collections and merge results ranked by distance.
        Returns the same format as a single query() call but with an extra
        'notebook_id' field in each metadata entry.
        """
        all_documents: list[str] = []
        all_metadatas: list[dict] = []
        all_distances: list[float] = []

        for nb_id in notebook_ids:
            try:
                collection = self.client.get_collection(name=self._collection_name(nb_id))
            except Exception:
                continue  # notebook collection doesn't exist yet

            if collection.count() == 0:
                continue

            result = collection.query(
                query_embeddings=query_emb,
                n_results=min(top_k, collection.count()),
            )

            docs = result.get("documents", [[]])[0]
            metas = result.get("metadatas", [[]])[0]
            dists = result.get("distances", [[]])[0] if result.get("distances") else []

            for i, (doc, meta) in enumerate(zip(docs, metas)):
                meta_with_nb = {**(meta if isinstance(meta, dict) else {}), "notebook_id": nb_id}
                all_documents.append(doc)
                all_metadatas.append(meta_with_nb)
                all_distances.append(dists[i] if i < len(dists) else float("inf"))

        # Sort by distance (best matches first) and take top_k
        if not all_documents:
            return {"documents": [[]], "metadatas": [[]], "distances": [[]]}

        ranked = sorted(
            zip(all_documents, all_metadatas, all_distances),
            key=lambda x: x[2],
        )[:top_k]

        return {
            "documents": [[r[0] for r in ranked]],
            "metadatas": [[r[1] for r in ranked]],
            "distances": [[r[2] for r in ranked]],
        }

    def _doc_summaries_collection_name(self, notebook_id: str) -> str:
        """Get the name of the document summaries collection."""
        return f"notebook_{notebook_id}_summaries"
    
    def store_document_summary(self, notebook_id: str, summary: DocumentSummary) -> None:
        """
        Store a document summary in a separate collection for fast document-level filtering.
        """
        summaries_collection = self.client.get_or_create_collection(
            name=self._doc_summaries_collection_name(notebook_id)
        )
        
        # Embed the summary for similarity search
        summary_embedding = self.embedding_backend.embed([summary.summary])

        # Store summary with metadata
        import hashlib
        # Use a stable, notebook-scoped summary id to avoid collisions/overwrites
        sid_input = f"{notebook_id}:{summary.source_path}:{summary.chunk_count}:{summary.summary[:64]}"
        sid = hashlib.md5(sid_input.encode()).hexdigest()
        summaries_collection.add(
            ids=[sid],
            documents=[summary.summary],
            metadatas=[{
                "source_path": summary.source_path,
                "chunk_count": summary.chunk_count,
                "document_type": summary.document_type or "unknown",
            }],
            embeddings=summary_embedding,
        )
    
    async def aquery_document_summaries(
        self,
        notebook_id: str,
        query: str,
        top_k: int = 3,
    ) -> list[DocumentSummary]:
        """Async variant: embedding runs on a threadpool."""
        try:
            summaries_collection = self.client.get_collection(
                name=self._doc_summaries_collection_name(notebook_id)
            )
        except Exception:
            return []
        query_emb = await self.embedding_backend.aembed([query])
        results = summaries_collection.query(query_embeddings=query_emb, n_results=top_k)
        return self._build_summaries(results)

    def query_document_summaries(
        self,
        notebook_id: str,
        query: str,
        top_k: int = 3,
    ) -> list[DocumentSummary]:
        """
        Query document summaries to find relevant documents (Stage 1: Coarse filtering).
        Returns summaries of documents that match the query.
        """
        try:
            summaries_collection = self.client.get_collection(
                name=self._doc_summaries_collection_name(notebook_id)
            )
        except Exception:
            # No summaries collection yet, return empty
            return []

        # Embed query and search summaries
        query_emb = self.embedding_backend.embed([query])
        results = summaries_collection.query(query_embeddings=query_emb, n_results=top_k)
        return self._build_summaries(results)

    def _build_summaries(self, results: dict) -> list[DocumentSummary]:
        
        # Convert to DocumentSummary objects
        summaries = []
        documents = results.get("documents", [[]])[0]
        metadatas = results.get("metadatas", [[]])[0]
        
        for doc, meta in zip(documents, metadatas):
            if isinstance(meta, dict):
                summaries.append(DocumentSummary(
                    source_path=meta.get("source_path", "unknown"),
                    summary=doc,
                    chunk_count=meta.get("chunk_count", 0),
                    document_type=meta.get("document_type"),
                ))
        
        return summaries
    
    def get_all_document_summaries(self, notebook_id: str) -> list[DocumentSummary]:
        """Get all document summaries for a notebook."""
        try:
            summaries_collection = self.client.get_collection(
                name=self._doc_summaries_collection_name(notebook_id)
            )
        except Exception:
            return []
        
        all_docs = summaries_collection.get(include=["documents", "metadatas"])
        documents = all_docs.get("documents", [])
        metadatas = all_docs.get("metadatas", [])
        
        summaries = []
        for doc, meta in zip(documents, metadatas):
            if isinstance(meta, dict):
                summaries.append(DocumentSummary(
                    source_path=meta.get("source_path", "unknown"),
                    summary=doc,
                    chunk_count=meta.get("chunk_count", 0),
                    document_type=meta.get("document_type"),
                ))
        
        return summaries


def create_vector_store(settings: AppConfig, embedding_backend: EmbeddingBackend) -> VectorStoreManager:
    # anonymized_telemetry=False keeps the offline promise intact and quiets
    # the "Failed to send telemetry event…" warnings that dominate logs.
    client = chromadb.PersistentClient(
        path=str(settings.index_dir),
        settings=chromadb.Settings(anonymized_telemetry=False),
    )
    return VectorStoreManager(client=client, embedding_backend=embedding_backend)
